<?php

return [
    'cities' => [
        'rabat' => [
            'name' => 'Rabat',
            'slug' => 'rabat',
            'image' => 'assets/OndaRabat.jpeg',
            'hero_image' => 'assets/OndaRabat.jpeg',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Rabat.',
        ],
        'casablanca' => [
            'name' => 'Casablanca',
            'slug' => 'casablanca',
            'image' => 'assets/VilleCasa.jpeg',
            'hero_image' => 'assets/VilleCasa.jpeg',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Casablanca.',
        ],
        'fes' => [
            'name' => 'Fès',
            'slug' => 'fes',
            'image' => 'assets/Acc2.png',
            'hero_image' => 'assets/Acc2.png',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Fès.',
        ],
        'tanger' => [
            'name' => 'Tanger',
            'slug' => 'tanger',
            'image' => 'assets/VilleTanger.jpeg',
            'hero_image' => 'assets/VilleTanger.jpeg',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Tanger.',
        ],
        'marrakech' => [
            'name' => 'Marrakech',
            'slug' => 'marrakech',
            'image' => 'assets/Villekesh.webp',
            'hero_image' => 'assets/Villekesh.webp',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Marrakech.',
        ],
        'ElHoceima' => [
            'name' => 'ElHoceima',
            'slug' => 'ElHoceima',
            'image' => 'assets/VilleHoceima.jpeg',
            'hero_image' => 'assets/VilleHoceima.jpeg',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville ElHoceima.',
        ],
        'Taghazout' => [
            'name' => 'Taghazout Bay',
            'slug' => 'Taghazout',
            'image' => 'assets/Taghazout3.jpeg',
            'hero_image' => 'assets/Taghazout3.jpeg',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville Taghazout.',
        ],
    ],
    'parkings' => [
        [
            'name' => 'Place Moulay El Hassan',
            'slug' => 'place-moulay-el-hassan',
            'city_slug' => 'rabat',
            'image' => 'assets/Mly2.png',
            'capacity' => 316,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'location' => 'Hassan, Rabat',
            'short_location' => 'Hassan',
            'lat' => 34.01639934653795,
            'lng' => -6.830347367014824,
            'description' => 'Un parking central offrant un accès direct aux zones commerçantes et administratives.',
        ],
        [
            'name' => 'Vegetal Hay Riad',
            'slug' => 'vegetal-hay-riad',
            'city_slug' => 'rabat',
            'image' => 'assets/HayRiad.png',
            'capacity' => 615,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'location' => 'Hay Riad, Rabat',
            'short_location' => 'Hay Riad',
             'lat' => 33.95773410686093, 
            'lng' => -6.8704471801900295,
            'description' => 'Une solution de stationnement adaptée à un quartier dynamique et à forte activité.',
        ],
        [
            'name' => 'Aeroport de Rabat Sale T1',
            'slug' => 'aeroport-rabat',
            'city_slug' => 'rabat',
            'image' => 'assets/OndaRabat.jpeg',
            'capacity' => 600,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'location' => 'Aeroport, Rabat',
            'short_location' => 'Aeroport',
             'lat' => 34.05050559918551,
            'lng' => -6.749434498149957,
            'description' => 'Un parking fonctionnel dédié aux voyageurs et aux flux de l’aéroport.',
        ],
        [
            'name' => 'Aeroport de Rabat Sale T2',
            'slug' => 'aeroport-rabat',
            'city_slug' => 'rabat',
            'image' => 'assets/OndaRabat.jpeg',
            'capacity' => 70,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'location' => 'Aeroport, Rabat',
            'short_location' => 'Aeroport',
             'lat' => 34.05050559918551,
            'lng' => -6.749434498149957,
            'description' => 'Parking dédié aux voyageurs, facilitant l’accès au terminal.',
        ],
         [
            'name' => 'Aeroport de Rabat Sale - Nouveau Terminal',
            'slug' => 'aeroport-rabat-nouveau-terminal',
            'city_slug' => 'rabat',
            'image' => 'assets/OndaRabat1.jpeg',
            'capacity' => 1536,
            'type' => 'sous-sol',
            'levels' => '1 niveau',
            'location' => 'Aeroport, Rabat',
            'short_location' => 'Aeroport',
             'lat' => 34.05090072131303, 
            'lng' => -6.74979818629212,
            'description' => 'Infrastructure moderne dédiée au développement du nouveau terminal.',
        ],
        
        [
            'name' => 'Marina',
            'slug' => 'marina',
            'city_slug' => 'casablanca',
            'image' => 'assets/CasaMarina.jpeg',
            'capacity' => 572,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'location' => 'Marina, Casablanca',
            'short_location' => 'Marina',
            'lat' => 33.60791150608259,
            'lng' => -7.623766815342883,
            'description' => 'Un parking intégré à un environnement urbain mêlant loisirs, bureaux et commerces.',
        ],
        [
            'name' => 'Casa Finance City',
            'slug' => 'casa-finance-city',
            'city_slug' => 'casablanca',
            'image' => 'assets/CFC.jpg',
            'capacity' => 1435,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'location' => 'CFC, Casablanca',
            'short_location' => 'CFC',
            'lat' => 33.562120783586444, 
            'lng' => -7.662794873446153,
            'description' => 'Une solution de stationnement au cœur d’un pôle économique et financier stratégique.',
        ],
        [
            'name' => 'Bab Jdid',
            'slug' => 'bab-jdid',
            'city_slug' => 'fes',
            'image' => 'assets/BabJdid.png',
            'capacity' => 913,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 34.05477052850458,  
            'lng' => -4.974368534396279,
            'location' => 'Bab Jdid , Fès',
            'short_location' => 'Bab Jdid',
            'description' => 'Un parking de proximité facilitant l’accès aux zones historiques et commerciales.',
        ],
        [
            'name' => 'Bab Hamra',
            'slug' => 'bab-hamra',
            'city_slug' => 'fes',
            'image' => 'assets/BabHamra.png',
            'capacity' => 210,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'lat' =>  34.06042639470905, 
            'lng' => -4.967128288367418,
            'location' => 'Bab Hamra, Fès',
            'short_location' => 'Bab Hamra',
            'description' => 'Une infrastructure conçue pour répondre aux besoins quotidiens d’un quartier actif.',
        ],
        
        [
            'name' => 'Bab Guissa',
            'slug' => 'bab-guissa',
            'city_slug' => 'fes',
            'image' => 'assets/BabGuissa.png',
            'capacity' => 152,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'lat' => 34.06996580230706,  
            'lng' => -4.975189234395612,
            'location' => 'Bab Guissa, Fès',
            'short_location' => 'Bab Guissa',
            'description' => 'Un espace de stationnement adapté aux flux résidentiels et urbains.',
        ],
        [
            'name' => 'Oued Zhoun',
            'slug' => 'oued-zhoun',
            'city_slug' => 'fes',
            'image' => 'assets/Oued.png',
            'capacity' => 112,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'lat' =>  34.06937195229214,
            'lng' =>  -4.971178488367036,
            'location' => 'Oued Zhoun, Fès',
            'short_location' => 'Oued Zhoun',
            'description' => 'Un parking central au service des usagers et des activités du centre-ville.',
        ],
        [
            'name' => 'Bounafae',
            'slug' => 'bounafae',
            'city_slug' => 'fes',
            'image' => 'assets/Bounafae.jpeg',
            'capacity' => 108,
            'type' => 'sous-sol',
            'levels' => '1 niveau',
            'lat' => 34.054769206279374, 
            'lng' =>  -4.974586732546232,
            'location' => 'Bounafae, Fès',
            'short_location' => 'ounafae',
            'description' => 'Une solution pratique pour les stationnements de courte durée et les déplacements urbains.',
        ],
        [
            'name' => 'Bin Lamdoun',
            'slug' => 'bin-lamdoun',
            'city_slug' => 'fes',
            'image' => 'assets/BinLam.png',
            'capacity' => 184,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 34.068973965464295, 
            'lng' =>  -4.968972246038462,
            'location' => 'Bin Lamdoun, Fès',
            'short_location' => 'Bin Lamdoun',
            'description' => 'Un parking contribuant à améliorer la fluidité dans un axe en développement.',
        ],
        [
            'name' => 'Ain Azliten',
            'slug' => 'ain-azliten',
            'city_slug' => 'fes',
            'image' => 'assets/AinAzliten.png',
            'capacity' => 224,
            'type' => 'surface',
            'levels' => '2 niveau',
            'lat' => 34.06450048637534,  
            'lng' => -4.981743819052997,
            'location' => 'Ain Azliten, Fès',
            'short_location' => 'Ain Azliten',
            'description' => 'Un espace de stationnement intégré aux parcours touristiques et de loisirs.',
        ],
        [
            'name' => 'Bab Boujloud',
            'slug' => 'fes-jnan-sbil',
            'city_slug' => 'fes',
            'image' => 'assets/BabBoujloud.png',
            'capacity' => 121,
            'type' => 'sous-sol',
            'levels' => '1 niveau',
            'lat' => 34.06177808009685,  
            'lng' => -4.984449190217419,
            'location' => 'Bab Boujloud, Fès',
            'short_location' => 'Bab Boujloud',
            'description' => 'Une solution facilitant l’accès aux sites culturels et zones à forte affluence.',
        ],
        [
            'name' => 'R CIF',
            'slug' => 'r-cif',
            'city_slug' => 'fes',
            'image' => 'assets/RCIF2.png',
            'capacity' => 100,
            'type' => 'sous-sol',
            'levels' => '2 niveau',
            'lat' =>  34.05473365079577, 
            'lng' => -4.974597461381952, 
            'location' => 'R CIF, Fès',
            'short_location' => 'R CIF',
            'description' => 'Un parking conçu pour accompagner les déplacements dans un environnement urbain.',
        ],
        [
            'name' => 'Aeroport de Fes-Saïss',
            'slug' => 'aeroport-de-fes-saïss',
            'city_slug' => 'fes',
            'image' => 'assets/AeroportFes.jpg',
            'capacity' => 1218,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' =>33.930847087969, 
            'lng' =>  -4.984158257671801,
            'location' => 'Aeroport de Fes-Saïss, Fès',
            'short_location' => 'Aeroport de Fes-Saïss',
            'description' => 'Une infrastructure dédiée aux voyageurs et aux activités de l’aéroport.',
        ],
        [
            'name' => 'La Corniche',
            'slug' => 'la-corniche',
            'city_slug' => 'tanger',
            'image' => 'assets/Corniche.jpeg',
            'capacity' => 190,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'location' => 'La Corniche, Tanger',
            'short_location' => 'La Corniche',
            'lat' => 35.781925250334, 
            'lng' => -5.766615013492839,
            'description' => 'Un parking au service d’un espace touristique et de détente en bord de mer.',
        ],
        [
            'name' => 'Aeroport international Marrakech-Menara',
            'slug' => 'aeroport',
            'city_slug' => 'marrakech',
            'image' => 'assets/Aeroportkesh.jpeg',
            'capacity' => 1415,
            'type' => 'surface',
            'levels' => '2 niveaux',
            'location' => 'Aeroport, Marrakech-Menara',
            'lat' => 31.601939007088212,  
            'lng' => -8.025560270320065,
            'short_location' => 'Aeroport',
            'description' => 'Une offre de stationnement premium intégrée à une destination urbaine à fort rayonnement.',
        ],
        [
            'name' => 'Aquapark ElHoceima',
            'slug' => 'aquapark-elhoceima',
            'city_slug' => 'ElHoceima',
            'image' => 'assets/Aquapark.jpeg',
            'capacity' => 80,
            'type' => 'surface',
            'levels' => '1 niveau',
            'location' => 'ELHoceima, Aquapark',
            'lat' => 35.20671836938501,
            'lng' => -3.8936668319869274, 
            'short_location' => 'Aquapark',
            'description' => 'Parking éphémère dédié aux visiteurs de l’aquapark.',
        ],
        [
            'name' => 'Taghazout P1',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 800,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Un espace de stationnement au cœur d’une destination touristique et balnéaire.',
        ],
        [
            'name' => 'Taghazout P2',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 100,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Parking moderne au sein d’un ensemble de stationnements.',
        ],
        [
            'name' => 'Taghazout P3',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 80,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Espace de stationnement pratique dans une zone regroupée.',
        ],
        [
            'name' => 'Taghazout P4',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 250,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Solution de stationnement au cœur d’un ensemble continu.',
        ],
        [
            'name' => 'Taghazout P5',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 41,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Parking fonctionnel dans une zone de stationnement unifiée.',
        ],
        [
            'name' => 'Taghazout P6',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 195,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Espace de stationnement sécurisé à proximité immédiate.',
        ],
        [
            'name' => 'Taghazout P7',
            'slug' => 'taghazout',
            'city_slug' => 'Taghazout',
            'image' => 'assets/Taghazout1.jpeg',
            'capacity' => 90,
            'type' => 'surface',
            'levels' => '1 niveau',
            'lat' => 30.527515153978214,
            'lng' => -9.6920717057047, 
            'location' => 'Taghazout',
            'short_location' => 'Agadir',
            'description' => 'Parking optimisé au sein d’un pôle de stationnement.',
        ],
    ],
];
