<?php

return [
    'cities' => [
        'rabat' => [
            'name' => 'Rabat',
            'slug' => 'rabat',
            'image' => 'assets/OndaRabat.jpeg',
            'hero_image' => 'assets/OndaRabat.jpeg',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Rabat.',
        ],
        'casablanca' => [
            'name' => 'Casablanca',
            'slug' => 'casablanca',
            'image' => 'assets/HayRiad2.png',
            'hero_image' => 'assets/HayRiad2.png',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Casablanca.',
        ],
        'fes' => [
            'name' => 'Fès',
            'slug' => 'fes',
            'image' => 'assets/Mly3.png',
            'hero_image' => 'assets/Mly3.png',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Fès.',
        ],
        'tanger' => [
            'name' => 'Tanger',
            'slug' => 'tanger',
            'image' => 'assets/HayRiad3.png',
            'hero_image' => 'assets/HayRiad3.png',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Tanger.',
        ],
        'marrakech' => [
            'name' => 'Marrakech',
            'slug' => 'marrakech',
            'image' => 'assets/Mly2.png',
            'hero_image' => 'assets/Mly2.png',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Marrakech.',
        ],
        'mohamadia' => [
            'name' => 'Mohamadia',
            'slug' => 'mohamadia',
            'image' => 'assets/HayRiad.png',
            'hero_image' => 'assets/HayRiad.png',
            'description' => 'Découvrez les parkings CGPark disponibles dans la ville de Mohamadia.',
        ],
    ],
    'parkings' => [
        [
            'name' => 'Arribat Center',
            'slug' => 'arribat-center',
            'city_slug' => 'rabat',
            'image' => 'assets/OndaRabat.jpeg',
            'capacity' => 520,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 5 MAD / heure',
            'subscriptions' => 'Abonnement mensuel et abonnement entreprise',
            'location' => 'Agdal, Rabat',
            'short_location' => 'Agdal',
            'description' => 'Parking premium situé au coeur d’un pôle commercial et de services, pensé pour offrir confort, fluidité et sécurité aux usagers.',
        ],
        [
            'name' => 'Bab El Had',
            'slug' => 'bab-el-had',
            'city_slug' => 'rabat',
            'image' => 'assets/Mly2.png',
            'capacity' => 360,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 4 MAD / heure',
            'subscriptions' => 'Abonnement résident et professionnel',
            'location' => 'Centre-ville, Rabat',
            'short_location' => 'Centre-ville',
            'description' => 'Une offre de stationnement centralisée pour accompagner la dynamique commerciale et administrative de Rabat.',
        ],
        [
            'name' => 'Bouregreg Marina',
            'slug' => 'bouregreg-marina',
            'city_slug' => 'rabat',
            'image' => 'assets/HayRiad.png',
            'capacity' => 410,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 6 MAD / heure',
            'subscriptions' => 'Abonnement mensuel et pass événementiel',
            'location' => 'Marina du Bouregreg, Rabat',
            'short_location' => 'Bouregreg',
            'description' => 'Parking moderne au service des visiteurs, riverains et professionnels d’un quartier en forte attractivité.',
        ],
        [
            'name' => 'Anfa Park',
            'slug' => 'anfa-park',
            'city_slug' => 'casablanca',
            'image' => 'assets/HayRiad2.png',
            'capacity' => 680,
            'type' => 'sous-sol',
            'levels' => '3 niveaux',
            'tariffs' => 'À partir de 6 MAD / heure',
            'subscriptions' => 'Abonnement mensuel et formule corporate',
            'location' => 'Anfa, Casablanca',
            'short_location' => 'Anfa',
            'description' => 'Parking de nouvelle génération au coeur d’un quartier mixte associant bureaux, commerces et espaces de vie.',
        ],
        [
            'name' => 'Casa Finance City',
            'slug' => 'casa-finance-city',
            'city_slug' => 'casablanca',
            'image' => 'assets/HayRiad3.png',
            'capacity' => 540,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 7 MAD / heure',
            'subscriptions' => 'Abonnement entreprise et accès résident',
            'location' => 'CFC, Casablanca',
            'short_location' => 'CFC',
            'description' => 'Une solution de stationnement haut de gamme pour accompagner la mobilité dans un quartier d’affaires structurant.',
        ],
        [
            'name' => 'Fès Médina Sud',
            'slug' => 'fes-medina-sud',
            'city_slug' => 'fes',
            'image' => 'assets/Mly3.png',
            'capacity' => 230,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 4 MAD / heure',
            'subscriptions' => 'Abonnement hebdomadaire et mensuel',
            'location' => 'Médina Sud, Fès',
            'short_location' => 'Médina Sud',
            'description' => 'Un parking de proximité destiné à fluidifier l’accès aux zones historiques et commerçantes.',
        ],
        [
            'name' => 'Fès Agdal',
            'slug' => 'fes-agdal',
            'city_slug' => 'fes',
            'image' => 'assets/Mly2.png',
            'capacity' => 310,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 5 MAD / heure',
            'subscriptions' => 'Abonnement mensuel',
            'location' => 'Agdal, Fès',
            'short_location' => 'Agdal',
            'description' => 'Infrastructure pensée pour accompagner les usages quotidiens d’un quartier à forte fréquentation.',
        ],
        [
            'name' => 'Fès Rass El Ma',
            'slug' => 'fes-rass-el-ma',
            'city_slug' => 'fes',
            'image' => 'assets/HayRiad.png',
            'capacity' => 185,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 3 MAD / heure',
            'subscriptions' => 'Abonnement commerçant',
            'location' => 'Rass El Ma, Fès',
            'short_location' => 'Rass El Ma',
            'description' => 'Un dispositif de stationnement de proximité pour soutenir les activités de quartier.',
        ],
        [
            'name' => 'Fès Atlas',
            'slug' => 'fes-atlas',
            'city_slug' => 'fes',
            'image' => 'assets/OndaRabat.jpeg',
            'capacity' => 260,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 4 MAD / heure',
            'subscriptions' => 'Abonnement résident',
            'location' => 'Atlas, Fès',
            'short_location' => 'Atlas',
            'description' => 'Une réponse de stationnement organisée pour les zones résidentielles et les flux pendulaires.',
        ],
        [
            'name' => 'Fès Centre',
            'slug' => 'fes-centre',
            'city_slug' => 'fes',
            'image' => 'assets/Mly.png',
            'capacity' => 340,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 5 MAD / heure',
            'subscriptions' => 'Abonnement entreprise et mensuel',
            'location' => 'Centre, Fès',
            'short_location' => 'Centre',
            'description' => 'Parking central au service des administrations, commerces et usagers du coeur de ville.',
        ],
        [
            'name' => 'Fès Gare',
            'slug' => 'fes-gare',
            'city_slug' => 'fes',
            'image' => 'assets/HayRiad2.png',
            'capacity' => 220,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 4 MAD / heure',
            'subscriptions' => 'Pass mobilité et abonnement mensuel',
            'location' => 'Zone Gare, Fès',
            'short_location' => 'Gare',
            'description' => 'Une solution pensée pour les usagers intermodaux et les stationnements de courte durée.',
        ],
        [
            'name' => 'Fès Route d’Imouzzer',
            'slug' => 'fes-route-imouzzer',
            'city_slug' => 'fes',
            'image' => 'assets/HayRiad3.png',
            'capacity' => 270,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 4 MAD / heure',
            'subscriptions' => 'Abonnement résident et professionnel',
            'location' => 'Route d’Imouzzer, Fès',
            'short_location' => 'Imouzzer',
            'description' => 'Parking dimensionné pour améliorer la fluidité dans un axe urbain en développement.',
        ],
        [
            'name' => 'Fès Jardin Jnan Sbil',
            'slug' => 'fes-jnan-sbil',
            'city_slug' => 'fes',
            'image' => 'assets/OndaRabat.jpeg',
            'capacity' => 205,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 3 MAD / heure',
            'subscriptions' => 'Abonnement visiteur et journalier',
            'location' => 'Jnan Sbil, Fès',
            'short_location' => 'Jnan Sbil',
            'description' => 'Une offre de stationnement intégrée aux parcours touristiques et de loisirs.',
        ],
        [
            'name' => 'Fès Borj Nord',
            'slug' => 'fes-borj-nord',
            'city_slug' => 'fes',
            'image' => 'assets/Mly2.png',
            'capacity' => 190,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 3 MAD / heure',
            'subscriptions' => 'Abonnement hebdomadaire',
            'location' => 'Borj Nord, Fès',
            'short_location' => 'Borj Nord',
            'description' => 'Un parking de desserte à proximité d’un site à forte fréquentation culturelle.',
        ],
        [
            'name' => 'Tanger City Port',
            'slug' => 'tanger-city-port',
            'city_slug' => 'tanger',
            'image' => 'assets/HayRiad3.png',
            'capacity' => 430,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 6 MAD / heure',
            'subscriptions' => 'Abonnement portuaire et mensuel',
            'location' => 'Port de Tanger, Tanger',
            'short_location' => 'City Port',
            'description' => 'Parking au service d’un pôle portuaire, touristique et commercial majeur.',
        ],
        [
            'name' => 'Marrakech M Avenue',
            'slug' => 'marrakech-m-avenue',
            'city_slug' => 'marrakech',
            'image' => 'assets/Mly.png',
            'capacity' => 480,
            'type' => 'sous-sol',
            'levels' => '2 niveaux',
            'tariffs' => 'À partir de 7 MAD / heure',
            'subscriptions' => 'Abonnement premium et abonnement mensuel',
            'location' => 'M Avenue, Marrakech',
            'short_location' => 'M Avenue',
            'description' => 'Une offre de stationnement premium intégrée à une destination urbaine à fort rayonnement.',
        ],
        [
            'name' => 'Mohamadia Central Park',
            'slug' => 'mohamadia-central-park',
            'city_slug' => 'mohamadia',
            'image' => 'assets/HayRiad.png',
            'capacity' => 260,
            'type' => 'surface',
            'levels' => '1 niveau',
            'tariffs' => 'À partir de 4 MAD / heure',
            'subscriptions' => 'Abonnement mensuel et pass commerçant',
            'location' => 'Centre, Mohamadia',
            'short_location' => 'Centre',
            'description' => 'Parking de proximité conçu pour répondre aux besoins du centre-ville et des usages quotidiens.',
        ],
    ],
];
